apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-app-argocd-pre-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tomKatzav96/Pre-Prod-Argo-Project
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: pre-prod

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
