# Values file

name: weather

replicaCount: 1

image:
  repository: tomkatzav/argo-weather:1.0.46
  pullPolicy: IfNotPresent

service:
  name: weather-service
  type: NodePort  
  portName: my-port
  protocol: TCP
  port: 5000
  targetPort: 5000
  nodePort: 30100


