# Values file

name: weather

replicaCount: 2

nameSpaces: pre-prod

image:
  repository: tomkatzav/argo-weather:1.0.76
  pullPolicy: IfNotPresent

service:
  name: weather-service
  type: NodePort 
  portName: my-port
  protocol: TCP
  port: 5000
  targetPort: 5000
  nodePort: 30111
